import type { DialogueOption, MonsterDef } from '../engine/types';

export const MONSTERS: MonsterDef[] = [
  {
    id: 'cow',
    name: 'Cow',
    maxHp: 8,
    atk: 1,
    str: 1,
    def: 1,
    drops: [{ itemId: 'raw-beef', weight: 100 }],
  },
  {
    id: 'goblin',
    name: 'Goblin',
    maxHp: 5,
    atk: 1,
    str: 1,
    def: 1,
    drops: [
      { itemId: 'goblin-meat', weight: 50 },
      { itemId: 'goblin-sword', weight: 25 },
    ],
    nothingWeight: 25,
  },
  {
    id: 'giant-rat',
    name: 'Giant Rat',
    combatLevel: 4,
    maxHp: 14,
    atk: 3,
    str: 3,
    def: 2,
    drops: [
      { itemId: 'raw-beef', weight: 55 },
      { itemId: 'junk', weight: 20 },
    ],
    nothingWeight: 25,
  },
  {
    id: 'giant-frog',
    name: 'Giant Frog',
    combatLevel: 9,
    maxHp: 22,
    atk: 6,
    str: 7,
    def: 5,
    drops: [
      { itemId: 'frog-legs', weight: 60 },
      { itemId: 'junk', weight: 15 },
    ],
    nothingWeight: 25,
  },
  {
    id: 'goblin-general',
    name: 'Grubeater',
    maxHp: 50,
    atk: 10,
    str: 10,
    def: 10,
    drops: [
      { itemId: 'goblin-meat', weight: 32 },
      { itemId: 'goblin-sword', weight: 8 },
      { itemId: 'goblin-mace', weight: 5 },
      { itemId: 'amulet-of-glory', weight: 4 },
      { itemId: 'goblin-club', weight: 2 },
    ],
    nothingWeight: 49,
  },
  {
    id: 'varrock-guard',
    name: 'Varrock Guard',
    maxHp: 25,
    atk: 5,
    str: 5,
    def: 5,
    drops: [
      { itemId: 'varrock-rations', weight: 32 },
      { itemId: 'steel-sword', weight: 8 },
      { itemId: 'addy-sword', weight: 2 },
      { itemId: 'rune-sword', weight: 1 },
    ],
    nothingWeight: 57,
  },
  {
    id: 'varrock-archer',
    name: 'Varrock Archer',
    maxHp: 20,
    atk: 10,
    str: 2,
    def: 1,
    drops: [
      { itemId: 'varrock-rations', weight: 32 },
      { itemId: 'steel-knuckles', weight: 8 },
      { itemId: 'addy-knuckles', weight: 2 },
      { itemId: 'rune-knuckles', weight: 1 },
    ],
    nothingWeight: 57,
  },
  {
    id: 'varrock-thug',
    name: 'Varrock Thug',
    combatLevel: 17,
    maxHp: 42,
    atk: 13,
    str: 15,
    def: 10,
    drops: [
      { itemId: 'varrock-rations', weight: 35 },
      { itemId: 'steel-sword', weight: 12 },
      { itemId: 'steel-knuckles', weight: 8 },
      { itemId: 'gold-bar', weight: 12 },
    ],
    nothingWeight: 33,
  },
  {
    id: 'dark-wizard',
    name: 'Dark Wizard',
    combatLevel: 41,
    maxHp: 88,
    atk: 38,
    str: 30,
    def: 20,
    drops: [
      { itemId: 'wizard-grub', weight: 40 },
      { itemId: 'gold-bar', weight: 20, quantity: 2 },
      { itemId: 'dark-wizard-hat', weight: 6 },
    ],
    nothingWeight: 34,
  },
  {
    id: 'varrock-general',
    name: 'Sir Lancelot',
    maxHp: 100,
    atk: 25,
    str: 20,
    def: 20,
    drops: [
      { itemId: 'varrock-rations', weight: 16 },
      { itemId: 'addy-sword', weight: 16 },
      { itemId: 'rune-sword', weight: 4 },
      { itemId: 'excalibur', weight: 1 },
    ],
    nothingWeight: 63,
  },
  {
    id: 'evil-wizard',
    name: 'Surok Magis',
    maxHp: 250,
    atk: 50,
    str: 50,
    def: 5,
    drops: [
      { itemId: 'wizard-grub', weight: 90 },
      { itemId: 'arcane-staff', weight: 2 },
    ],
    nothingWeight: 8,
  },
  {
    id: 'falador-guard',
    name: 'Falador Guard',
    maxHp: 38,
    atk: 8,
    str: 8,
    def: 14,
    drops: [
      { itemId: 'varrock-rations', weight: 30 },
      { itemId: 'steel-sword', weight: 10 },
      { itemId: 'addy-sword', weight: 2 },
      { itemId: 'gold-bar', weight: 3 },
    ],
    nothingWeight: 55,
  },
  {
    id: 'dwarven-miner',
    name: 'Dwarven Miner',
    maxHp: 46,
    atk: 9,
    str: 15,
    def: 9,
    drops: [
      { itemId: 'gold-bar', weight: 24 },
      { itemId: 'steel-knuckles', weight: 8 },
      { itemId: 'addy-knuckles', weight: 2 },
      { itemId: 'varrock-rations', weight: 16 },
    ],
    nothingWeight: 50,
  },
  {
    id: 'white-knight-squire',
    name: 'White Knight Squire',
    combatLevel: 23,
    maxHp: 60,
    atk: 16,
    str: 15,
    def: 22,
    drops: [
      { itemId: 'varrock-rations', weight: 30 },
      { itemId: 'steel-platebody', weight: 8 },
      { itemId: 'steel-kiteshield', weight: 8 },
      { itemId: 'gold-bar', weight: 14 },
    ],
    nothingWeight: 40,
  },
  {
    id: 'mine-scorpion',
    name: 'Deep Mine Scorpion',
    combatLevel: 30,
    maxHp: 55,
    atk: 24,
    str: 22,
    def: 16,
    drops: [
      { itemId: 'gold-bar', weight: 25, quantity: 2 },
      { itemId: 'varrock-rations', weight: 20 },
      { itemId: 'scorpion-stinger', weight: 6 },
    ],
    nothingWeight: 49,
  },
  {
    id: 'sir-kitbreaker',
    name: 'Sir Kitbreaker',
    maxHp: 165,
    atk: 34,
    str: 30,
    def: 30,
    drops: [
      { itemId: 'varrock-rations', weight: 20 },
      { itemId: 'addy-sword', weight: 12 },
      { itemId: 'rune-sword', weight: 5 },
      { itemId: 'excalibur', weight: 1 },
      { itemId: 'gold-bar', weight: 12, quantity: 2 },
    ],
    nothingWeight: 50,
  },
  {
    id: 'count-draynor',
    name: 'Count Draynor',
    combatLevel: 34,
    maxHp: 48,
    atk: 13,
    str: 15,
    def: 11,
    drops: [
      { itemId: 'wizard-grub', weight: 42 },
      { itemId: 'gold-bar', weight: 28, quantity: 2 },
      { itemId: 'prayer-potion', weight: 5 },
      { itemId: 'vampyre-cape', weight: 5 },
      { itemId: 'sharpened-stake', weight: 5 },
    ],
    nothingWeight: 15,
  },
  {
    id: 'manor-ghoul',
    name: 'Manor Ghoul',
    combatLevel: 22,
    maxHp: 46,
    atk: 15,
    str: 17,
    def: 12,
    drops: [
      { itemId: 'wizard-grub', weight: 35 },
      { itemId: 'gold-bar', weight: 25 },
      { itemId: 'prayer-potion', weight: 3 },
    ],
    nothingWeight: 37,
  },
  {
    id: 'general-graardor',
    name: 'General Graardor',
    combatLevel: 624,
    maxHp: 255,
    atk: 64,
    str: 58,
    def: 55,
    drops: [
      { itemId: 'war-god-ration', weight: 300, quantity: 2 },
      { itemId: 'manta', weight: 200, quantity: 2 },
      { itemId: 'gold-bar', weight: 150, quantity: 8 },
      { itemId: 'prayer-potion', weight: 60, quantity: 2 },
      { itemId: 'rune-sword', weight: 50 },
      { itemId: 'bandos-chestplate', weight: 20 },
      { itemId: 'bandos-tassets', weight: 20 },
      { itemId: 'bandos-boots', weight: 25 },
      { itemId: 'graardor-warhammer', weight: 15 },
      { itemId: 'bandos-hilt', weight: 10 },
      { itemId: 'godsword-shard-1', weight: 10 },
      { itemId: 'godsword-shard-2', weight: 10 },
      { itemId: 'godsword-shard-3', weight: 10 },
    ],
    nothingWeight: 120,
  },
  {
    id: 'commander-zilyana',
    name: 'Commander Zilyana',
    combatLevel: 596,
    maxHp: 255,
    atk: 72,
    str: 50,
    def: 60,
    drops: [
      { itemId: 'war-god-ration', weight: 300, quantity: 2 },
      { itemId: 'manta', weight: 200, quantity: 2 },
      { itemId: 'gold-bar', weight: 150, quantity: 8 },
      { itemId: 'prayer-potion', weight: 60, quantity: 2 },
      { itemId: 'rune-sword', weight: 50 },
      { itemId: 'saradomin-sword', weight: 20 },
      { itemId: 'armadyl-crossbow', weight: 15 },
      { itemId: 'saradomin-hilt', weight: 10 },
      { itemId: 'godsword-shard-1', weight: 10 },
      { itemId: 'godsword-shard-2', weight: 10 },
      { itemId: 'godsword-shard-3', weight: 10 },
    ],
    nothingWeight: 165,
  },
  {
    id: 'kril-tsutsaroth',
    name: "K'ril Tsutsaroth",
    combatLevel: 650,
    maxHp: 280,
    atk: 70,
    str: 64,
    def: 48,
    drops: [
      { itemId: 'war-god-ration', weight: 300, quantity: 2 },
      { itemId: 'manta', weight: 200, quantity: 2 },
      { itemId: 'gold-bar', weight: 150, quantity: 8 },
      { itemId: 'prayer-potion', weight: 60, quantity: 2 },
      { itemId: 'rune-sword', weight: 50 },
      { itemId: 'zamorakian-spear', weight: 20 },
      { itemId: 'steam-battlestaff', weight: 15 },
      { itemId: 'zamorak-hilt', weight: 10 },
      { itemId: 'godsword-shard-1', weight: 10 },
      { itemId: 'godsword-shard-2', weight: 10 },
      { itemId: 'godsword-shard-3', weight: 10 },
    ],
    nothingWeight: 165,
  },
  {
    id: 'kreearra',
    name: "Kree'arra",
    combatLevel: 580,
    maxHp: 255,
    atk: 76,
    str: 54,
    def: 58,
    drops: [
      { itemId: 'war-god-ration', weight: 300, quantity: 2 },
      { itemId: 'manta', weight: 200, quantity: 2 },
      { itemId: 'gold-bar', weight: 150, quantity: 8 },
      { itemId: 'prayer-potion', weight: 60, quantity: 2 },
      { itemId: 'rune-sword', weight: 50 },
      { itemId: 'armadyl-helmet', weight: 20 },
      { itemId: 'armadyl-chestplate', weight: 20 },
      { itemId: 'armadyl-chainskirt', weight: 25 },
      { itemId: 'armadyl-hilt', weight: 10 },
      { itemId: 'godsword-shard-1', weight: 10 },
      { itemId: 'godsword-shard-2', weight: 10 },
      { itemId: 'godsword-shard-3', weight: 10 },
    ],
    nothingWeight: 135,
  },
  {
    id: 'spiritual-warrior',
    name: 'Spiritual Warrior',
    // Footsoldiers, not commanders: they guard the nexus on the way in.
    combatLevel: 240,
    maxHp: 210,
    atk: 56,
    str: 52,
    def: 48,
    drops: [
      { itemId: 'war-god-ration', weight: 30, quantity: 2 },
      { itemId: 'manta', weight: 25 },
      { itemId: 'gold-bar', weight: 30, quantity: 5 },
      { itemId: 'rune-sword', weight: 6 },
      { itemId: 'prayer-potion', weight: 12 },
    ],
    nothingWeight: 22,
  },
  {
    id: 'spiritual-mage',
    name: 'Spiritual Mage',
    combatLevel: 285,
    maxHp: 235,
    atk: 68,
    str: 58,
    def: 52,
    drops: [
      { itemId: 'war-god-ration', weight: 25, quantity: 2 },
      { itemId: 'manta', weight: 25, quantity: 2 },
      { itemId: 'gold-bar', weight: 30, quantity: 6 },
      { itemId: 'prayer-potion', weight: 12 },
      { itemId: 'spiritual-sigil', weight: 5 },
    ],
    nothingWeight: 25,
  },
  {
    id: 'ghast',
    name: 'Ghast',
    combatLevel: 30,
    maxHp: 38,
    atk: 9,
    str: 11,
    def: 7,
    drops: [
      { itemId: 'swamp-ration', weight: 45 },
      { itemId: 'gold-bar', weight: 25, quantity: 2 },
      { itemId: 'ancient-totem', weight: 3 },
    ],
    nothingWeight: 27,
  },
  {
    id: 'giant-swamp-snail',
    name: 'Giant Swamp Snail',
    combatLevel: 20,
    maxHp: 32,
    atk: 6,
    str: 8,
    def: 13,
    drops: [
      { itemId: 'swamp-snail-meat', weight: 70 },
      { itemId: 'swamp-snelm', weight: 8 },
      { itemId: 'gold-bar', weight: 10 },
    ],
    nothingWeight: 12,
  },
  {
    id: 'morytania-vampyre',
    name: 'Morytania Vampyre',
    combatLevel: 61,
    maxHp: 78,
    atk: 23,
    str: 25,
    def: 20,
    drops: [
      { itemId: 'swamp-ration', weight: 40 },
      { itemId: 'vampyre-cape', weight: 10 },
      { itemId: 'vampyre-coat', weight: 5 },
      { itemId: 'gold-bar', weight: 25, quantity: 3 },
    ],
    nothingWeight: 20,
  },
  {
    id: 'swamp-banshee',
    name: 'Swamp Banshee',
    combatLevel: 45,
    maxHp: 74,
    atk: 30,
    str: 26,
    def: 22,
    drops: [
      { itemId: 'swamp-ration', weight: 35 },
      { itemId: 'gold-bar', weight: 25, quantity: 2 },
      { itemId: 'swamp-snelm', weight: 6 },
      { itemId: 'prayer-potion', weight: 5 },
    ],
    nothingWeight: 29,
  },
  {
    id: 'tz-kek',
    name: 'Tz-Kek',
    combatLevel: 45,
    maxHp: 60,
    atk: 25,
    str: 28,
    def: 20,
    drops: [
      { itemId: 'lava-eel', weight: 45 },
      { itemId: 'gold-bar', weight: 25, quantity: 4 },
      { itemId: 'tzhaar-gauntlets', weight: 10 },
      { itemId: 'tzhaar-ket-om', weight: 5 },
      { itemId: 'obsidian-shield', weight: 5 },
    ],
    nothingWeight: 10,
  },
  {
    id: 'tz-kih',
    name: 'Tz-Kih',
    combatLevel: 90,
    maxHp: 120,
    atk: 42,
    str: 40,
    def: 34,
    drops: [
      { itemId: 'lava-eel', weight: 40 },
      { itemId: 'gold-bar', weight: 30, quantity: 3 },
      { itemId: 'tzhaar-gauntlets', weight: 5 },
    ],
    nothingWeight: 25,
  },
  {
    id: 'yt-mejkot',
    name: 'Yt-MejKot',
    combatLevel: 210,
    maxHp: 260,
    atk: 62,
    str: 58,
    def: 55,
    drops: [
      { itemId: 'lava-eel', weight: 35, quantity: 2 },
      { itemId: 'gold-bar', weight: 30, quantity: 5 },
      { itemId: 'obsidian-cape', weight: 8 },
      { itemId: 'prayer-potion', weight: 10 },
    ],
    nothingWeight: 17,
  },
  {
    id: 'ket-zek',
    name: 'Ket-Zek',
    combatLevel: 360,
    maxHp: 300,
    atk: 78,
    str: 70,
    def: 72,
    drops: [
      { itemId: 'lava-eel', weight: 40, quantity: 2 },
      { itemId: 'gold-bar', weight: 30, quantity: 6 },
      { itemId: 'tzhaar-ket-om', weight: 8 },
      { itemId: 'obsidian-shield', weight: 8 },
    ],
    nothingWeight: 14,
  },
  {
    id: 'tztok-jad',
    name: 'TzTok-Jad',
    combatLevel: 702,
    maxHp: 1000,
    atk: 210,
    str: 250,
    def: 180,
    drops: [{ itemId: 'fire-cape', weight: 100 }],
  },
  {
    id: 'dragon-whelp',
    name: 'Dragon Whelp',
    combatLevel: 55,
    maxHp: 95,
    atk: 32,
    str: 34,
    def: 28,
    drops: [
      { itemId: 'dragon-steak', weight: 40 },
      { itemId: 'dragon-bones', weight: 25 },
      { itemId: 'gold-bar', weight: 25, quantity: 3 },
    ],
    nothingWeight: 10,
  },
  {
    id: 'elvarg',
    name: 'Elvarg',
    combatLevel: 83,
    maxHp: 180,
    atk: 45,
    str: 52,
    def: 42,
    drops: [
      { itemId: 'dragon-steak', weight: 40 },
      { itemId: 'gold-bar', weight: 30, quantity: 10 },
      { itemId: 'prayer-potion', weight: 10 },
      { itemId: 'dragon-bones', weight: 18 },
      { itemId: 'rune-platebody', weight: 2 },
    ],
  },
  {
    id: 'dagannoth-rex',
    name: 'Dagannoth Rex',
    combatLevel: 303,
    maxHp: 420,
    atk: 84,
    str: 82,
    def: 92,
    drops: [
      { itemId: 'manta', weight: 350, quantity: 2 },
      { itemId: 'gold-bar', weight: 250, quantity: 15 },
      { itemId: 'prayer-potion', weight: 60, quantity: 2 },
      { itemId: 'dragon-axe', weight: 25 },
      { itemId: 'berserker-ring', weight: 20 },
      { itemId: 'warrior-ring', weight: 20 },
    ],
    nothingWeight: 275,
  },
  {
    id: 'dagannoth-spawn',
    name: 'Dagannoth Spawn',
    combatLevel: 130,
    maxHp: 165,
    atk: 50,
    str: 48,
    def: 55,
    drops: [
      { itemId: 'manta', weight: 40 },
      { itemId: 'gold-bar', weight: 30, quantity: 5 },
      { itemId: 'prayer-potion', weight: 8 },
    ],
    nothingWeight: 22,
  },
  {
    id: 'grave-skeleton',
    name: 'Graveyard Skeleton',
    combatLevel: 35,
    maxHp: 45,
    atk: 16,
    str: 18,
    def: 14,
    drops: [
      { itemId: 'bone-broth', weight: 40 },
      { itemId: 'bone-arrows', weight: 20, quantity: 5 },
      { itemId: 'gold-bar', weight: 20, quantity: 2 },
    ],
    nothingWeight: 20,
  },
  {
    id: 'grave-skeleton-archer',
    name: 'Skeleton Archer',
    combatLevel: 42,
    maxHp: 52,
    atk: 22,
    str: 16,
    def: 15,
    drops: [
      { itemId: 'bone-arrows', weight: 40, quantity: 8 },
      { itemId: 'bone-broth', weight: 25 },
      { itemId: 'gold-bar', weight: 20, quantity: 2 },
    ],
    nothingWeight: 15,
  },
  {
    id: 'crypt-wraith',
    name: 'Crypt Wraith',
    combatLevel: 90,
    maxHp: 130,
    atk: 44,
    str: 40,
    def: 36,
    drops: [
      { itemId: 'bone-broth', weight: 35 },
      { itemId: 'bone-arrows', weight: 20, quantity: 8 },
      { itemId: 'gold-bar', weight: 25, quantity: 3 },
      { itemId: 'prayer-potion', weight: 5 },
    ],
    nothingWeight: 15,
  },
  {
    id: 'grave-titan',
    name: 'Grave Titan',
    combatLevel: 220,
    maxHp: 300,
    atk: 66,
    str: 70,
    def: 60,
    drops: [
      { itemId: 'bone-broth', weight: 30, quantity: 2 },
      { itemId: 'gold-bar', weight: 30, quantity: 8 },
      { itemId: 'bone-boots', weight: 8 },
      { itemId: 'bone-gauntlets', weight: 8 },
      { itemId: 'prayer-potion', weight: 10 },
    ],
    nothingWeight: 14,
  },
  {
    id: 'bones-skeleton-king',
    name: 'Bones, the Skeleton King',
    combatLevel: 420,
    maxHp: 500,
    atk: 92,
    str: 105,
    def: 88,
    drops: [
      { itemId: 'bone-broth', weight: 300, quantity: 2 },
      { itemId: 'gold-bar', weight: 250, quantity: 20 },
      { itemId: 'prayer-potion', weight: 60, quantity: 2 },
      { itemId: 'bone-crown', weight: 30 },
      { itemId: 'bone-plate', weight: 25 },
      { itemId: 'bone-greaves', weight: 30 },
      { itemId: 'bone-gauntlets', weight: 35 },
      { itemId: 'bone-boots', weight: 40 },
      { itemId: 'bone-shield', weight: 30 },
      { itemId: 'bone-amulet', weight: 40 },
      { itemId: 'bone-arrows', weight: 70, quantity: 20 },
      { itemId: 'possessed-femur', weight: 20 },
    ],
    nothingWeight: 70,
  },
  {
    id: 'orc-grunt',
    name: "Kor'kron Grunt",
    combatLevel: 340,
    maxHp: 340,
    atk: 84,
    str: 90,
    def: 72,
    drops: [
      { itemId: 'war-god-ration', weight: 35, quantity: 2 },
      { itemId: 'gold-bar', weight: 30, quantity: 10 },
      { itemId: 'orc-warboots', weight: 5 },
      { itemId: 'prayer-potion', weight: 10 },
    ],
    nothingWeight: 20,
  },
  {
    id: 'korkron-elite',
    name: "Kor'kron Elite",
    combatLevel: 470,
    maxHp: 400,
    atk: 96,
    str: 104,
    def: 82,
    drops: [
      { itemId: 'war-god-ration', weight: 30, quantity: 2 },
      { itemId: 'gold-bar', weight: 30, quantity: 14 },
      { itemId: 'orc-warhelm', weight: 6 },
      { itemId: 'orc-warplate', weight: 4 },
      { itemId: 'prayer-potion', weight: 10 },
    ],
    nothingWeight: 20,
  },
  /* --- Warriors' Guild: the defender grind ------------------------------ */
  {
    id: 'cyclops',
    name: 'Cyclops',
    combatLevel: 76,
    maxHp: 108,
    atk: 38,
    str: 40,
    def: 42,
    drops: [
      { itemId: 'cyclops-hide', weight: 40 },
      { itemId: 'varrock-rations', weight: 24 },
      { itemId: 'gold-bar', weight: 24, quantity: 3 },
      { itemId: 'steel-kiteshield', weight: 6 },
    ],
    nothingWeight: 26,
  },
  {
    id: 'elder-cyclops',
    name: 'Elder Cyclops',
    combatLevel: 112,
    maxHp: 160,
    atk: 54,
    str: 56,
    def: 58,
    drops: [
      { itemId: 'cyclops-hide', weight: 40, quantity: 2 },
      { itemId: 'manta', weight: 25 },
      { itemId: 'gold-bar', weight: 25, quantity: 6 },
      { itemId: 'prayer-potion', weight: 8 },
    ],
    nothingWeight: 22,
  },

  /* --- Barrows: six wights, each with their own kit -------------------- */
  {
    id: 'ahrim',
    name: 'Ahrim the Blighted',
    combatLevel: 98,
    maxHp: 150,
    atk: 52,
    str: 44,
    def: 40,
    drops: [
      { itemId: 'barrows-key', weight: 240 },
      { itemId: 'manta', weight: 200 },
      { itemId: 'gold-bar', weight: 180, quantity: 6 },
      { itemId: 'prayer-potion', weight: 90 },
      { itemId: 'ahrims-hood', weight: 60 },
      { itemId: 'ahrims-top', weight: 40 },
      { itemId: 'ahrims-skirt', weight: 45 },
      { itemId: 'ahrims-staff', weight: 30 },
    ],
    nothingWeight: 115,
  },
  {
    id: 'dharok',
    name: 'Dharok the Wretched',
    combatLevel: 118,
    maxHp: 200,
    atk: 56,
    str: 68,
    def: 52,
    drops: [
      { itemId: 'barrows-key', weight: 240 },
      { itemId: 'manta', weight: 200 },
      { itemId: 'gold-bar', weight: 180, quantity: 6 },
      { itemId: 'prayer-potion', weight: 90 },
      { itemId: 'dharoks-helm', weight: 60 },
      { itemId: 'dharoks-platebody', weight: 40 },
      { itemId: 'dharoks-platelegs', weight: 45 },
      { itemId: 'dharoks-greataxe', weight: 30 },
    ],
    nothingWeight: 115,
  },
  {
    id: 'guthan',
    name: 'Guthan the Infested',
    combatLevel: 110,
    maxHp: 180,
    atk: 58,
    str: 58,
    def: 54,
    drops: [
      { itemId: 'barrows-key', weight: 240 },
      { itemId: 'manta', weight: 200 },
      { itemId: 'gold-bar', weight: 180, quantity: 6 },
      { itemId: 'prayer-potion', weight: 90 },
      { itemId: 'guthans-helm', weight: 60 },
      { itemId: 'guthans-platebody', weight: 40 },
      { itemId: 'guthans-chainskirt', weight: 45 },
      { itemId: 'guthans-warspear', weight: 30 },
    ],
    nothingWeight: 115,
  },
  {
    id: 'karil',
    name: 'Karil the Tainted',
    combatLevel: 102,
    maxHp: 160,
    atk: 72,
    str: 46,
    def: 44,
    drops: [
      { itemId: 'barrows-key', weight: 240 },
      { itemId: 'manta', weight: 200 },
      { itemId: 'gold-bar', weight: 180, quantity: 6 },
      { itemId: 'prayer-potion', weight: 90 },
      { itemId: 'karils-coif', weight: 60 },
      { itemId: 'karils-leathertop', weight: 40 },
      { itemId: 'karils-leatherskirt', weight: 45 },
      { itemId: 'karils-crossbow', weight: 30 },
    ],
    nothingWeight: 115,
  },
  {
    id: 'torag',
    name: 'Torag the Corrupted',
    combatLevel: 108,
    maxHp: 190,
    atk: 52,
    str: 60,
    def: 62,
    drops: [
      { itemId: 'barrows-key', weight: 240 },
      { itemId: 'manta', weight: 200 },
      { itemId: 'gold-bar', weight: 180, quantity: 6 },
      { itemId: 'prayer-potion', weight: 90 },
      { itemId: 'torags-helm', weight: 60 },
      { itemId: 'torags-platebody', weight: 40 },
      { itemId: 'torags-platelegs', weight: 45 },
      { itemId: 'torags-hammers', weight: 30 },
    ],
    nothingWeight: 115,
  },
  {
    id: 'verac',
    name: 'Verac the Defiled',
    combatLevel: 114,
    maxHp: 185,
    atk: 60,
    str: 60,
    def: 48,
    drops: [
      { itemId: 'barrows-key', weight: 240 },
      { itemId: 'manta', weight: 200 },
      { itemId: 'gold-bar', weight: 180, quantity: 6 },
      { itemId: 'prayer-potion', weight: 90 },
      { itemId: 'veracs-helm', weight: 60 },
      { itemId: 'veracs-brassard', weight: 40 },
      { itemId: 'veracs-plateskirt', weight: 45 },
      { itemId: 'veracs-flail', weight: 30 },
    ],
    nothingWeight: 115,
  },
  {
    id: 'ghost-of-barrows',
    name: 'Crypt Guardian',
    combatLevel: 88,
    maxHp: 120,
    atk: 44,
    str: 42,
    def: 38,
    drops: [
      { itemId: 'bone-broth', weight: 35 },
      { itemId: 'gold-bar', weight: 30, quantity: 3 },
      { itemId: 'barrows-key', weight: 12 },
      { itemId: 'prayer-potion', weight: 6 },
    ],
    nothingWeight: 17,
  },
  {
    id: 'high-overlord-saurfang',
    name: 'High Overlord Saurfang',
    combatLevel: 550,
    maxHp: 420,
    atk: 100,
    str: 112,
    def: 86,
    drops: [
      { itemId: 'war-god-ration', weight: 300, quantity: 2 },
      { itemId: 'gold-bar', weight: 250, quantity: 20 },
      { itemId: 'prayer-potion', weight: 75, quantity: 2 },
      { itemId: 'saurfang-cleaver', weight: 25 },
      { itemId: 'orc-warplate', weight: 30 },
      { itemId: 'orc-warboots', weight: 40 },
    ],
    nothingWeight: 280,
  },
  {
    id: 'orc-king-thrall',
    name: 'Orc King Thrall',
    combatLevel: 700,
    maxHp: 700,
    atk: 120,
    str: 130,
    def: 105,
    drops: [
      { itemId: 'war-god-ration', weight: 300, quantity: 3 },
      { itemId: 'gold-bar', weight: 250, quantity: 30 },
      { itemId: 'prayer-potion', weight: 75, quantity: 2 },
      { itemId: 'doomhammer', weight: 15 },
      { itemId: 'orc-warplate', weight: 30 },
      { itemId: 'orc-warboots', weight: 40 },
      { itemId: 'ancient-totem', weight: 50 },
    ],
    nothingWeight: 240,
  },
];

/** Curated collection-log uniques. Supplies and ordinary gold drops are omitted. */
export const MONSTER_UNIQUES: Record<string, string[]> = {
  ahrim: ['ahrims-hood', 'ahrims-top', 'ahrims-skirt', 'ahrims-staff'],
  dharok: ['dharoks-helm', 'dharoks-platebody', 'dharoks-platelegs', 'dharoks-greataxe'],
  guthan: ['guthans-helm', 'guthans-platebody', 'guthans-chainskirt', 'guthans-warspear'],
  karil: ['karils-coif', 'karils-leathertop', 'karils-leatherskirt', 'karils-crossbow'],
  torag: ['torags-helm', 'torags-platebody', 'torags-platelegs', 'torags-hammers'],
  verac: ['veracs-helm', 'veracs-brassard', 'veracs-plateskirt', 'veracs-flail'],
  cyclops: ['cyclops-hide'],
  'elder-cyclops': ['cyclops-hide'],
  'ghost-of-barrows': ['barrows-key'],
  goblin: ['goblin-sword'],
  'varrock-thug': ['steel-knuckles'],
  'dark-wizard': ['dark-wizard-hat'],
  'white-knight-squire': ['steel-platebody'],
  'mine-scorpion': ['scorpion-stinger'],
  'swamp-banshee': ['swamp-snelm'],
  'tz-kih': ['tzhaar-gauntlets'],
  'yt-mejkot': ['obsidian-cape'],
  'dragon-whelp': ['dragon-bones'],
  'crypt-wraith': ['bone-arrows'],
  'grave-titan': ['bone-boots', 'bone-gauntlets'],
  'orc-grunt': ['orc-warboots'],
  'korkron-elite': ['orc-warhelm', 'orc-warplate'],
  'spiritual-mage': ['spiritual-sigil'],
  'goblin-general': ['goblin-sword', 'goblin-mace', 'goblin-club', 'amulet-of-glory'],
  'varrock-guard': ['addy-sword', 'rune-sword'],
  'varrock-archer': ['addy-knuckles', 'rune-knuckles'],
  'varrock-general': ['addy-sword', 'rune-sword', 'excalibur'],
  'evil-wizard': ['arcane-staff'],
  'falador-guard': ['addy-sword'],
  'dwarven-miner': ['addy-knuckles'],
  'sir-kitbreaker': ['rune-sword', 'excalibur'],
  'count-draynor': ['vampyre-cape', 'sharpened-stake'],
  'general-graardor': [
    'bandos-chestplate',
    'bandos-tassets',
    'bandos-boots',
    'graardor-warhammer',
    'bandos-hilt',
    'godsword-shard-1',
    'godsword-shard-2',
    'godsword-shard-3',
  ],
  'commander-zilyana': [
    'saradomin-sword',
    'armadyl-crossbow',
    'saradomin-hilt',
    'godsword-shard-1',
    'godsword-shard-2',
    'godsword-shard-3',
  ],
  'kril-tsutsaroth': [
    'zamorakian-spear',
    'steam-battlestaff',
    'zamorak-hilt',
    'godsword-shard-1',
    'godsword-shard-2',
    'godsword-shard-3',
  ],
  kreearra: [
    'armadyl-helmet',
    'armadyl-chestplate',
    'armadyl-chainskirt',
    'armadyl-hilt',
    'godsword-shard-1',
    'godsword-shard-2',
    'godsword-shard-3',
  ],
  ghast: ['ancient-totem'],
  'giant-swamp-snail': ['swamp-snelm'],
  'morytania-vampyre': ['vampyre-cape', 'vampyre-coat'],
  'tz-kek': ['tzhaar-gauntlets', 'tzhaar-ket-om', 'obsidian-shield'],
  'ket-zek': ['tzhaar-ket-om', 'obsidian-shield'],
  'tztok-jad': ['fire-cape'],
  elvarg: ['rune-platebody'],
  'dagannoth-rex': ['dragon-axe', 'berserker-ring', 'warrior-ring'],
  'grave-skeleton': ['bone-arrows'],
  'grave-skeleton-archer': ['bone-arrows'],
  'bones-skeleton-king': [
    'bone-crown',
    'bone-plate',
    'bone-greaves',
    'bone-gauntlets',
    'bone-boots',
    'bone-shield',
    'bone-amulet',
    'bone-arrows',
    'possessed-femur',
  ],
  'high-overlord-saurfang': ['saurfang-cleaver', 'orc-warplate', 'orc-warboots'],
  'orc-king-thrall': ['doomhammer', 'orc-warplate', 'orc-warboots', 'ancient-totem'],
};

export const monsterMap = new Map(MONSTERS.map((m) => [m.id, m]));

export function getMonster(id: string): MonsterDef {
  const monster = monsterMap.get(id);
  if (!monster) throw new Error(`Unknown monster: ${id}`);
  return monster;
}

export function getMonsterCombatLevel(monsterOrId: MonsterDef | string): number {
  const monster = typeof monsterOrId === 'string' ? getMonster(monsterOrId) : monsterOrId;
  if (monster.combatLevel) return monster.combatLevel;
  return Math.max(
    1,
    Math.round((monster.atk + monster.str + monster.def + monster.maxHp / 4) / 3)
  );
}

/**
 * Bonus experience for the kill itself, on top of the experience earned per
 * point of damage. Weighted by both the creature's life and its combat level,
 * so a long fight against something dangerous is worth more than a long fight
 * against something merely fat.
 */
export function getMonsterKillXp(monsterOrId: MonsterDef | string): number {
  const monster = typeof monsterOrId === 'string' ? getMonster(monsterOrId) : monsterOrId;
  return Math.round(monster.maxHp * 0.5 + getMonsterCombatLevel(monster) * 2);
}

export function getMonsterUniqueDrops(monsterId: string): string[] {
  return MONSTER_UNIQUES[monsterId] ?? [];
}

/**
 * Creatures with enough of a mind to hold a conversation. Right-clicking one
 * offers "Talk to" alongside "Attack" — plenty of them would rather posture
 * than fight, and a few will tell you something worth knowing.
 *
 * Beasts are deliberately absent: cows, rats, dagannoths and Jad have nothing
 * to say to anybody.
 */
export const MONSTER_DIALOGUES: Record<string, DialogueOption[]> = {
  goblin: [
    { label: 'Greet it', text: 'Yaaa! Human come to goblin place! Goblin no like!' },
    { label: 'Ask about the chief', text: 'Grubeater big. Grubeater eat grubs. You no ask more.' },
  ],
  'goblin-general': [
    { label: 'Demand he leave', text: 'GRUBEATER take crops. Grubeater take YOU. Come closer, little thing.' },
    { label: 'Offer a bribe', text: 'You give food? ...Grubeater still smash. But eat first.' },
  ],
  'varrock-guard': [
    { label: 'Ask about the city', text: 'Move along. The square is watched, and I am watching it.' },
    { label: 'Ask about the thugs', text: 'Southeast cobbles, after dark. Take a friend, or take a sword.' },
  ],
  'varrock-thug': [
    { label: 'Talk him down', text: 'Walk away and we never met. Stay, and we settle it the loud way.' },
  ],
  'varrock-general': [
    { label: 'Ask for passage', text: 'Sir Lancelot holds this square. Best me and it is yours to cross.' },
    { label: 'Compliment his armour', text: 'Flattery is armour of its own. Neither will stop my blade.' },
  ],
  'evil-wizard': [
    { label: 'Ask what he wants', text: 'Surok Magis wants the crown, the city, and quiet. In that order.' },
    { label: 'Threaten him', text: 'Threats. From a thing with one life and no library.' },
  ],
  'dark-wizard': [
    { label: 'Ask about the circle', text: 'We read what Varrock burned. Ask again and you will be a footnote.' },
  ],
  'white-knight-squire': [
    { label: 'Ask about the trial', text: 'Beat five of us and Sir Tiffy signs your tabard. Nobody said it was fair.' },
  ],
  'dwarven-miner': [
    { label: 'Ask about the mine', text: 'Scorpions in the apron, ore in the dark, and no pay for either.' },
  ],
  'count-draynor': [
    { label: 'Ask about the manor', text: 'My house, my hours, my terms. You are early for dinner.' },
    { label: 'Ask about Ava', text: 'She hammers through the night and calls me the monster.' },
  ],
  'morytania-vampyre': [
    { label: 'Ask about the swamp', text: 'The bog keeps what it takes. I only keep what I drink.' },
  ],
  'tz-kek': [
    { label: 'Greet it', text: 'JalYt-Ket. You walk where the rock is thin. Walk carefully.' },
  ],
  'ket-zek': [
    { label: 'Ask about the arena', text: 'TzTok-Jad waits above. I decide who reaches the stair. Not you.' },
  ],
  'bones-skeleton-king': [
    { label: 'Address the king', text: 'You stand in my court wearing skin. How embarrassing for you.' },
    { label: 'Ask about the crown', text: 'It was heavy when I had a head for it. Take it, if you can lift you own.' },
    { label: 'Ask about the graveyard', text: 'Everyone here stayed. That is all a kingdom really needs.' },
  ],
  'general-graardor': [
    { label: 'Ask why he fights', text: 'Bandos said war. War is simple. I am good at simple.' },
  ],
  'commander-zilyana': [
    { label: 'Ask about the war', text: 'Four armies in one cave, and every one certain it is the righteous one.' },
  ],
  'kril-tsutsaroth': [
    { label: 'Speak to it', text: 'Zamorak takes the strong and laughs at the rest. Which are you?' },
  ],
  kreearra: [
    { label: 'Speak to it', text: 'The sky was ours. This ceiling is an insult we will outlive.' },
  ],
  'spiritual-warrior': [
    { label: 'Ask about the nexus', text: 'We fell holding this bridge. We hold it still. Nobody told us to stop.' },
  ],
  'spiritual-mage': [
    { label: 'Ask about the wards', text: 'The wards burn on the memory of men who no longer exist. Mine included.' },
  ],
  'orc-king-thrall': [
    { label: 'Greet the warchief', text: 'Lok-tar. You came a long way to be measured. Stand straight.' },
    { label: 'Ask about the Horde', text: 'The Horde is not a war. It is a promise we keep badly and keep anyway.' },
    { label: 'Ask for a fight', text: 'Good. Honour is easier to give than to explain.' },
  ],
  'high-overlord-saurfang': [
    { label: 'Ask about the ring', text: 'Every grunt out there wants my place. Most only want the story of it.' },
    { label: 'Ask about honour', text: 'Honour is what stops a victory from becoming a slaughter. Remember that today.' },
  ],
  'orc-grunt': [
    { label: 'Greet it', text: 'Lok-tar! You want the ring? Take a number, soft-skin.' },
  ],
  'korkron-elite': [
    { label: 'Greet it', text: "Kor'kron do not spar. If we raise an axe, someone is carried out." },
  ],
  'elder-cyclops': [
    { label: 'Greet it', text: 'Little warrior wants little shield. Earn it. Ten more, then ten more.' },
  ],
  ahrim: [{ label: 'Speak to the wight', text: 'I had almost finished the incantation. Almost. Stay — help me end it.' }],
  dharok: [{ label: 'Speak to the wight', text: 'It hurts less the closer I get to nothing. Come and see.' }],
  guthan: [{ label: 'Speak to the wight', text: 'The spear is thirsty. It has been thirsty for a very long time.' }],
  karil: [{ label: 'Speak to the wight', text: 'Stand still. It is quicker for both of us, and I am a good shot.' }],
  torag: [{ label: 'Speak to the wight', text: 'Nothing gets through. Not blades. Not years. Not you.' }],
  verac: [{ label: 'Speak to the wight', text: 'Your armour is a comfort. Comforts are what I break first.' }],
};

export function getMonsterDialogues(monsterId: string): DialogueOption[] {
  return MONSTER_DIALOGUES[monsterId] ?? [];
}

export function canTalkToMonster(monsterId: string): boolean {
  return getMonsterDialogues(monsterId).length > 0;
}
