import type { ItemDef } from '../engine/types';

export const ITEMS: ItemDef[] = [
  { id: 'gold-bar', name: 'Gold Bar', value: 100, category: 'misc' },
  { id: 'junk', name: 'Junk', value: 0, category: 'misc' },
  { id: 'vampyre-cape', name: 'Vampyre Cape', value: 750, category: 'armor', slot: 'cape', def: 4 },
  { id: 'bandos-chestplate', name: 'Bandos Chestplate', value: 500000, category: 'armor', slot: 'body', def: 55, str: 8, prayerBonus: 1 },
  { id: 'bandos-tassets', name: 'Bandos Tassets', value: 450000, category: 'armor', slot: 'legs', def: 42, str: 6, prayerBonus: 1 },
  { id: 'bandos-boots', name: 'Bandos Boots', value: 150000, category: 'armor', slot: 'feet', def: 12, str: 2, prayerBonus: 1 },
  { id: 'armadyl-helmet', name: 'Armadyl Helmet', value: 300000, category: 'armor', slot: 'helm', atk: 8, def: 28, prayerBonus: 1 },
  { id: 'armadyl-chestplate', name: 'Armadyl Chestplate', value: 600000, category: 'armor', slot: 'body', atk: 18, def: 50, prayerBonus: 1 },
  { id: 'armadyl-chainskirt', name: 'Armadyl Chainskirt', value: 550000, category: 'armor', slot: 'legs', atk: 14, def: 42, prayerBonus: 1 },
  { id: 'bandos-hilt', name: 'Bandos Godsword Hilt', value: 300000, category: 'misc' },
  { id: 'saradomin-hilt', name: 'Saradomin Godsword Hilt', value: 300000, category: 'misc' },
  { id: 'zamorak-hilt', name: 'Zamorak Godsword Hilt', value: 300000, category: 'misc' },
  { id: 'armadyl-hilt', name: 'Armadyl Godsword Hilt', value: 300000, category: 'misc' },
  { id: 'godsword-shard-1', name: 'Godsword Shard 1', value: 50000, category: 'misc' },
  { id: 'godsword-shard-2', name: 'Godsword Shard 2', value: 50000, category: 'misc' },
  { id: 'godsword-shard-3', name: 'Godsword Shard 3', value: 50000, category: 'misc' },
  { id: 'dragon-bones', name: 'Dragon Bones', value: 2500, category: 'misc' },
  { id: 'ancient-totem', name: 'Ancient Totem', value: 10000, category: 'misc' },
  { id: 'swamp-snelm', name: 'Swamp Snelm', value: 1200, category: 'armor', slot: 'helm', def: 10 },
  { id: 'vampyre-coat', name: 'Vampyre Coat', value: 6000, category: 'armor', slot: 'body', atk: 2, def: 18 },
  { id: 'obsidian-shield', name: 'Toktz-ket-xil', value: 30000, category: 'armor', slot: 'shield', str: 5, def: 30 },
  { id: 'tzhaar-gauntlets', name: 'TzHaar Gauntlets', value: 18000, category: 'armor', slot: 'hands', str: 3, def: 15 },
  { id: 'fire-cape', name: 'Fire Cape', value: 250000, category: 'armor', slot: 'cape', atk: 5, str: 10, def: 20, prayerBonus: 2 },
  { id: 'rune-platebody', name: 'Rune Platebody', value: 65000, category: 'armor', slot: 'body', def: 40 },
  { id: 'berserker-ring', name: 'Berserker Ring', value: 180000, category: 'armor', slot: 'ring', str: 8 },
  { id: 'warrior-ring', name: 'Warrior Ring', value: 140000, category: 'armor', slot: 'ring', atk: 8, def: 2 },
  { id: 'bone-crown', name: 'Bone Crown', value: 250000, category: 'armor', slot: 'helm', str: 3, def: 35, prayerBonus: 2 },
  { id: 'bone-plate', name: 'Bone Plate', value: 600000, category: 'armor', slot: 'body', str: 8, def: 65, prayerBonus: 1 },
  { id: 'bone-greaves', name: 'Bone Greaves', value: 450000, category: 'armor', slot: 'legs', str: 6, def: 50, prayerBonus: 1 },
  { id: 'bone-gauntlets', name: 'Bone Gauntlets', value: 220000, category: 'armor', slot: 'hands', str: 4, def: 25, prayerBonus: 1 },
  { id: 'bone-boots', name: 'Bone Boots', value: 180000, category: 'armor', slot: 'feet', str: 3, def: 22, prayerBonus: 1 },
  { id: 'bone-shield', name: 'Bone Shield', value: 300000, category: 'armor', slot: 'shield', str: 4, def: 45, prayerBonus: 2 },
  { id: 'bone-amulet', name: 'Bone Amulet', value: 160000, category: 'armor', slot: 'neck', str: 3, def: 10, prayerBonus: 4 },
  { id: 'bone-arrows', name: 'Bone Arrows', value: 12000, category: 'armor', slot: 'ammo', atk: 8 },
  { id: 'orc-warplate', name: 'Orc Warplate', value: 700000, category: 'armor', slot: 'body', str: 10, def: 58 },
  { id: 'orc-warboots', name: 'Orc Warboots', value: 260000, category: 'armor', slot: 'feet', str: 5, def: 24 },

  /* Mid-tier drops from the creatures that bridge each region's level gap. */
  { id: 'dark-wizard-hat', name: 'Dark Wizard Hat', value: 2500, category: 'armor', slot: 'helm', def: 4, prayerBonus: 3 },
  { id: 'scorpion-stinger', name: 'Scorpion Stinger', value: 1800, category: 'weapon', atk: 14, str: 12, attackSpeed: 3 },
  { id: 'obsidian-cape', name: 'Obsidian Cape', value: 22000, category: 'armor', slot: 'cape', str: 3, def: 12 },
  { id: 'orc-warhelm', name: 'Orc Warhelm', value: 40000, category: 'armor', slot: 'helm', str: 3, def: 22 },
  { id: 'spiritual-sigil', name: 'Spiritual Sigil', value: 95000, category: 'armor', slot: 'neck', def: 6, prayerBonus: 6 },

  /* Regional shop stock. Each keeper carries something nobody else sells. */
  { id: 'knight-tabard', name: 'White Knight Tabard', value: 3000, category: 'armor', slot: 'body', def: 16, prayerBonus: 2 },
  { id: 'avas-assembler', name: "Ava's Assembler", value: 8000, category: 'armor', slot: 'cape', atk: 6, def: 4 },
  { id: 'swamp-cloak', name: 'Swamp Cloak', value: 900, category: 'armor', slot: 'cape', def: 6, prayerBonus: 1 },
  { id: 'ossuary-charm', name: 'Ossuary Charm', value: 3500, category: 'armor', slot: 'neck', def: 2, prayerBonus: 4 },
  { id: 'orcish-cleaver', name: 'Orcish Cleaver', value: 25000, category: 'weapon', atk: 30, str: 40, attackSpeed: 5 },
  { id: 'steel-full-helm', name: 'Steel Full Helm', value: 250, category: 'armor', slot: 'helm', def: 5 },
  { id: 'adventurer-cape', name: 'Adventurer Cape', value: 100, category: 'armor', slot: 'cape', def: 2, prayerBonus: 1 },
  { id: 'bronze-amulet', name: 'Bronze Amulet', value: 150, category: 'armor', slot: 'neck', atk: 1, str: 1, def: 1, prayerBonus: 1 },
  { id: 'steel-arrows', name: 'Steel Arrows', value: 200, category: 'armor', slot: 'ammo', atk: 3 },
  { id: 'steel-platebody', name: 'Steel Platebody', value: 750, category: 'armor', slot: 'body', def: 12 },
  { id: 'steel-kiteshield', name: 'Steel Kiteshield', value: 450, category: 'armor', slot: 'shield', def: 8 },
  { id: 'steel-platelegs', name: 'Steel Platelegs', value: 600, category: 'armor', slot: 'legs', def: 10 },
  { id: 'leather-gloves', name: 'Leather Gloves', value: 75, category: 'armor', slot: 'hands', def: 2 },
  { id: 'leather-boots', name: 'Leather Boots', value: 75, category: 'armor', slot: 'feet', def: 2 },
  { id: 'copper-ring', name: 'Copper Ring', value: 125, category: 'armor', slot: 'ring', str: 1 },
  { id: 'bronze-sword', name: 'Bronze Sword', value: 15, category: 'weapon', atk: 5, str: 5, attackSpeed: 4 },
  { id: 'slimy-sword', name: 'Slimy Sword', value: 100, category: 'weapon', atk: 7, str: 7, attackSpeed: 4 },
  { id: 'goblin-sword', name: 'Goblin Sword', value: 200, category: 'weapon', atk: 2, str: 5, attackSpeed: 4 },
  { id: 'goblin-mace', name: 'Goblin Mace', value: 1000, category: 'weapon', atk: 5, str: 20, attackSpeed: 5 },
  { id: 'goblin-club', name: 'Goblin Club', value: 10000, category: 'weapon', atk: 15, str: 30, attackSpeed: 6 },
  { id: 'rune-scim', name: 'Rune Scimitar', value: 5000, category: 'weapon', atk: 20, str: 20, attackSpeed: 4 },
  { id: 'steel-sword', name: 'Steel Sword', value: 250, category: 'weapon', atk: 5, str: 8, attackSpeed: 4 },
  { id: 'addy-sword', name: 'Adamant Sword', value: 1000, category: 'weapon', atk: 10, str: 14, attackSpeed: 4 },
  { id: 'rune-sword', name: 'Rune Sword', value: 4000, category: 'weapon', atk: 16, str: 21, attackSpeed: 4 },
  { id: 'excalibur', name: 'Excalibur', value: 20000, category: 'weapon', atk: 50, str: 50, prayerBonus: 1, attackSpeed: 4 },
  { id: 'steel-knuckles', name: 'Steel Knuckles', value: 250, category: 'weapon', atk: 2, str: 15, attackSpeed: 3 },
  { id: 'addy-knuckles', name: 'Adamant Knuckles', value: 1000, category: 'weapon', atk: 4, str: 30, attackSpeed: 3 },
  { id: 'rune-knuckles', name: 'Rune Knuckles', value: 4000, category: 'weapon', atk: 10, str: 60, attackSpeed: 3 },
  { id: 'arcane-staff', name: 'Arcane Staff', value: 20000, category: 'weapon', atk: 100, str: 25, attackSpeed: 5 },
  { id: 'graardor-warhammer', name: "Graardor's Warhammer", value: 650000, category: 'weapon', atk: 68, str: 98, attackSpeed: 6 },
  { id: 'saradomin-sword', name: 'Saradomin Sword', value: 400000, category: 'weapon', atk: 92, str: 76, prayerBonus: 2, attackSpeed: 4 },
  { id: 'armadyl-crossbow', name: 'Armadyl Crossbow', value: 700000, category: 'weapon', atk: 118, str: 48, prayerBonus: 1, attackSpeed: 5 },
  { id: 'zamorakian-spear', name: 'Zamorakian Spear', value: 450000, category: 'weapon', atk: 88, str: 84, prayerBonus: 2, attackSpeed: 4 },
  { id: 'steam-battlestaff', name: 'Steam Battlestaff', value: 300000, category: 'weapon', atk: 108, str: 42, attackSpeed: 5 },
  { id: 'tzhaar-ket-om', name: 'Tzhaar-ket-om', value: 70000, category: 'weapon', atk: 45, str: 70, attackSpeed: 6 },
  { id: 'possessed-femur', name: 'Possessed Femur', value: 750000, category: 'weapon', atk: 75, str: 105, attackSpeed: 5 },
  { id: 'dragon-axe', name: 'Dragon Axe', value: 180000, category: 'weapon', atk: 60, str: 72, attackSpeed: 5 },
  { id: 'doomhammer', name: 'Doomhammer', value: 1000000, category: 'weapon', atk: 105, str: 125, attackSpeed: 6 },
  { id: 'saurfang-cleaver', name: "Saurfang's Cleaver", value: 600000, category: 'weapon', atk: 92, str: 108, attackSpeed: 5 },
  { id: 'prayer-potion', name: 'Prayer Potion', value: 1500, category: 'potion', prayerRestore: 25 },
  { id: 'shrimp', name: 'Shrimp', value: 5, category: 'food', heal: 5 },
  { id: 'trout', name: 'Trout', value: 10, category: 'food', heal: 10 },
  { id: 'shark', name: 'Shark', value: 50, category: 'food', heal: 20 },
  { id: 'manta', name: 'Manta Ray', value: 100, category: 'food', heal: 30 },
  { id: 'raw-beef', name: 'Raw Beef', value: 5, category: 'food', heal: 5 },
  { id: 'goblin-meat', name: 'Goblin Meat', value: 5, category: 'food', heal: 10 },
  { id: 'varrock-rations', name: 'Varrock Rations', value: 20, category: 'food', heal: 20 },
  { id: 'wizard-grub', name: 'Wizard Grub', value: 50, category: 'food', heal: 30 },
  { id: 'war-god-ration', name: 'War-God Ration', value: 250, category: 'food', heal: 50 },
  { id: 'swamp-snail-meat', name: 'Swamp Snail Meat', value: 45, category: 'food', heal: 18 },
  { id: 'swamp-ration', name: 'Swamp Ration', value: 70, category: 'food', heal: 25 },
  { id: 'lava-eel', name: 'Lava Eel', value: 150, category: 'food', heal: 35 },
  { id: 'dragon-steak', name: 'Dragon Steak', value: 300, category: 'food', heal: 45 },
  { id: 'bone-broth', name: 'Bone Broth', value: 200, category: 'food', heal: 40 },
  { id: 'frog-legs', name: 'Frog Legs', value: 25, category: 'food', heal: 12 },
  { id: 'shire-pie', name: 'Shire Pie', value: 60, category: 'food', heal: 22 },
];

export const itemMap = new Map(ITEMS.map((item) => [item.id, item]));

export function getItem(id: string): ItemDef {
  const item = itemMap.get(id);
  if (!item) throw new Error(`Unknown item: ${id}`);
  return item;
}
